# Generated by Django 5.0.1 on 2024-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planchas', models.PositiveIntegerField()),
                ('CMYK', models.PositiveIntegerField()),
                ('orden_CMYK', models.PositiveIntegerField()),
                ('orden_Planchas', models.PositiveIntegerField()),
            ],
        ),
    ]
